package exceptiondemo;

import java.util.Scanner;

public class ExceptionOne {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		int i;
		int j;
		
		Scanner scan=new Scanner(System.in);
		
		i=scan.nextInt();
		j=scan.nextInt();
		
		
		try
		{
			System.out.println(i/j);
		}
		catch(Exception e)
		{
			System.out.println(e.getMessage());
		}

	}

}


